config/routes.rb
Rails.application.routes.draw do
  root 'maestros#index'
  resources :maestros
end

app/models/maestro.rb
class Maestro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maestros_controller.rb
class MaestrosController < ApplicationController

  before_action :find_maestro, only: [:show, :edit, :update, :destroy]

  def index
    @maestros = Maestro.order(:artist)
  end

  def show
  end

  def new
    @maestro = Maestro.new
  end

  def create
    @maestro = Maestro.new(mae_params)
    if maestro.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @maestro.update_attributes(mae_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @maestro.destroy
    redirect_to action: :index
  end


  private

  def find_maestro
    @maestro = Maestro.find(params[:id])
  end

  def mae_params
    params.require(:maestro).permit(:artist, :album, :genre, :favorite)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicaMaestro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Musica Maestro!</h1>

<%= yield %>

</body>
</html>

app/views/maestros/_form.html.erb
<%= form_for @maestro do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%=f.label :album %>
  <%=f.text_field :album %>

  <%= f.label :genre%>
  <%= f.text_field :genre %>

  <%= f.label :favorite %>
  <%= f.check_box :favorite %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to the Music!", root_path %>

app/views/maestros/edit.html.erb
<%= render "form" %>

app/views/maestros/index.html.erb
<ul>
  <% @maestros.each do |maestro| %>
    <li>
      <% if maestro.favorite %> * <% end %>
      <b><%= maestro.artist %></b>
      <%= "|" %>
      <%= maestro.album %>
      <%= "|" %>
      <i><%= maestro.genre %></i>
      <%= link_to "Show", maestro_path(maestro) %>
      <%= link_to "Edit", edit_maestro_path(maestro) %>
      <!-- Need to define method: :delete -->
      <%= link_to "Remove", maestro_path(maestro), method: :delete %>
    </li>
    <% end %>
</ul>

<%= link_to "Add Artist and Album", new_maestro_path %>

app/views/maestros/new.html.erb
<%= render "form" %>

app/views/maestros/show.html.erb
<h3><%= @maestro.artist %></h3>

  <p><%= @maestro.album %></p>

  <p><%= @maestro.genre %></p>

  <p><% if @maestro.favorite %> (This is MY JAM!!!) <% end %></p>

  <p><%= link_to "Music List", maestros_path %></p>